### PR TITLE
Fix: Getting rid of dup code

### LINKED ISSUE #9: Duplicate code between `diff()` and `distance()`
The initial implementation seems to have caused some duplicate code between both methods defined for the implementations of the `StringDiffAlgorithm` trait. 

One reason the `distance()` method exists is that it's less memory-intensive. It always returns a `usize` type (statically-sized), since it's guaranteed to either be 32-bit or 64-bit integer. as creating a struct requires allocating memory. 

`diff()` allocates more memory since it's creating instances of `StringDiffOp`s, and also returns a vector, where vectors are a DST (dynamically-sized type), and therefore heap-allocated.

----

Is there a way we can deduplicate the code? The alternative is to let the library user call the `len()` method, like:
```rs
let hamming = HammingDistance {};
let distance: usize = hamming.diff().len();
```

What happens though, as mentioned above, is that if they only *need* the distance, then it's allocating memory that'll never be used. On the other hand, it'll be a maintenance burden to manage both duplicate implementations, and it'll be easier for bugs to pop up. Thoughts?

### PR DESCRIPTION
**Pull request by notalfredo**
Fixes #9

I had a different approach let me know what you think. For levenshtein distance I converted the matrix computations functions as a helper function. Then diff and distance call this helper function. This way we don't have any dupe code. Hamming works similar. 

On hamming.rs line 4 I added that unnecessary line. Ill fix it after I get feedback from the code.

### CODE REVIEW

File: src/hamming.rs [hunk 1]
```diff
@@ -22,17 +23,7 @@ impl StringDiffAlgorithm for HammingDistance {
...
-		} else {
-			let mut edit_distance: usize = 0;
-			for i in 0..s1.len() {
-				if s1.chars().nth(i).unwrap() != s2.chars().nth(i).unwrap() {
-					edit_distance += 1;
-				}
-			}
-			edit_distance
-		}
+        self.diff(s1, s2).len()
```
Comment (neoncitylights) [inline src/hamming.rs]: Since this line is inside the scope of a function, can you add a tab?

File: src/levenshtein.rs [hunk 2]
```diff
@@ -154,39 +152,18 @@ impl StringDiffAlgorithm for LevenshteinDistance {
...
 			}
 		}
+        dir_vector
+    }
 
-		LevenshteinDistance::get_operations(&dir_vector, s2, s1)
+}
+impl StringDiffAlgorithm for LevenshteinDistance {
+	fn diff<'a>(&self, s1: &'a str, s2: &'a str) -> Vec<StringDiffOp> {
+        let dir_matrix = LevenshteinDistance::get_operation_matrix(s1, s2);
```
Comment (neoncitylights) [inline src/levenshtein.rs]: Since this line is inside the scope of a function, can you add a tab?

File: src/levenshtein.rs [hunk 3]
```diff
@@ -154,39 +152,18 @@ impl StringDiffAlgorithm for LevenshteinDistance {
...
-				}
-				dist_vector[i][j] = LevenshteinDistance::min_dist(
-					dist_vector[i - 1][j] + 1,
-					dist_vector[i][j - 1] + 1,
-					dist_vector[i - 1][j - 1] + sub_cost,
-				);
-			}
-		}
-		dist_vector[second_string_len][first_string_len]
+        let dir_matrix = LevenshteinDistance::get_operation_matrix(s1, s2);
```
Comment (neoncitylights) [inline src/levenshtein.rs]: Since this line is inside the scope of a function, can you add a tab?

**Review by neoncitylights — CHANGES_REQUESTED** [review]

**Review by neoncitylights — APPROVED** [review]
