### PR TITLE
fix: allow insertion at any element in apply_diff()

### LINKED ISSUE #26: bug: `apply_diff()` only allows inserting characters at the end, not in the middle
When you pass in an insert operation to `apply_diff` with an index that's somewhere within the middle of the string, the character always get inserted at the end instead. To reproduce:

```rs
fn main() {
   let text = String::from("Hey");
   let diff_ops = vec![
       StringDiffOp::new_insert('e', 1),
       StringDiffOp::new_insert('e', 2),
   ];

   // this will cause a panic, instead it results in "Heyee"
   assert_eq!("Hey", apply_diff(text, diff_ops));
}
```

----

In this match arm inside of `apply_diff()`:
```rs
StringDiffOpKind::Insert(_x) => {
	new_string.push(_x);
}
```

Where `new_string` is a `String` type, the [`push()`](https://doc.rust-lang.org/std/string/struct.String.html#method.push) method inserts a character at the end. Instead, we should use the existing method [`insert()`](https://doc.rust-lang.org/std/string/struct.String.html#method.insert), which accepts an index (usize) and a character (char).

This bug fix also needs new test cases to make sure the `apply_diff()` function works as intended.

### PR DESCRIPTION
**Pull request by notalfredo**
fixes #26

### CODE REVIEW

**Comment by neoncitylights** [comment]
Could you rename this to `fix: allow insertion at any element in apply_diff()`? This is because:
 - we should stay consistent with tense in commit messages
 - we should be specific about what feature allowing this in
 - change the prefix to `fix: ` since we're fixing a bug, the other way it sounds like we're introducing one :P

**Review by neoncitylights — APPROVED** [review]

File: crates/differ/src/apply_diff.rs [hunk 1]
```diff
@@ -66,5 +74,10 @@ mod tests {
 			super::apply_diff("Saturday", test_vec_2)
 		);
 		assert_eq!(String::from("SETS"), super::apply_diff("RESET", test_vec_3));
+		assert_eq!(String::from("heeoy"), super::apply_diff("hey", test_vec_4));
+		assert_eq!(
+			String::from("skater"),
+			super::apply_diff("kate", test_vec_5)
+		);
```
Comment (neoncitylights) [inline crates/differ/src/apply_diff.rs:81]: In a future commit, can we make it so these assert_eq! statements are more consistent in style? Thanks!

**Review by neoncitylights — APPROVED** [review]

**Review by neoncitylights — APPROVED** [review]
In a future commit, can we make it so these assert_eq! statements are more consistent in style? Some are broken up in multiple lines, others are on the same line. Thanks!
